name: Lint on release

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup environment
      uses: ruby/setup-ruby@v1.182.0
      with:
        ruby-version: '3.0.1'
        bundler-cache: true
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: latest-stable
    - name: Lint the pod
      run: |
        bundle
        bundle exec pod lib lint --allow-warnings --verbose
