name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup environment
      uses: ruby/setup-ruby@v1.182.0
      with:
        ruby-version: '3.0.1'
        bundler-cache: true
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: latest-stable
    - name: Build and test
      run: |
        bundle
        xcodebuild test -project "nmbr-icu.xcprojct" -scheme "nmbr-icu" -destination "platform=iOS Simulator,name=iPhone 15"
