name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup environment
      uses: ruby/setup-ruby@v1.84.0
      with:
        ruby-version: '3.0.1'
        bundler-cache: true
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@vv1.4.0
      with:
        xcode-version: latest-stable
    - name: Build and test
    - run: |
      bundle
      xcodebuild test -workspace "Example/nmbr.xcworkspace" -scheme "nmbr-Example" -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13"
      bundle exec pod lib lint --allow-warnings
